Split docker build in more steps regarding dependent libraries: one per library.

diff --git a/cpp-client/Dockerfile b/cpp-client/Dockerfile
--- a/cpp-client/Dockerfile
+++ b/cpp-client/Dockerfile
@@ -2,14 +2,17 @@
 # Copyright (c) Deephaven Data Labs. All rights reserved.
 #
 
-FROM ubuntu:jammy AS dh-cpp-client
+FROM ubuntu:22.04
+ARG DEBIAN_FRONTEND=noninteractive
 
 #
 # Install system dependencies (eg, build tools) for build.
 #
-ENV DEBIAN_FRONTEND=noninteractive
-RUN apt-get update && \
-    apt-get install -y \
+RUN set -eux; \
+    apt-get -qq update && \
+    apt-get -qq -y --no-install-recommends install \
+            locales \
+            ca-certificates \
             curl \
             git \
             g++ \
@@ -17,16 +20,43 @@ RUN apt-get update && \
             make \
             build-essential \
             zlib1g-dev \
-            libssl-dev && \
-    apt-get clean
+            libssl-dev; \
+    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen; \
+    locale-gen en_US.UTF-8; \
+    apt-get clean; \
+    rm -rf /var/lib/apt/lists/*
 
 #
-# Download and build dependent libraries.
+# Download and build dependent libraries, each as its own separate step.
 #
-RUN mkdir -p /cpp-client/deps
-COPY build-dependencies.sh /cpp-client/deps
 WORKDIR /cpp-client/deps
-RUN bash -c "/cpp-client/deps/build-dependencies.sh && rm -fr /cpp-client/deps/src"
+# Be mindful about the order below:
+# 1. Some libraries have cross dependencies (eg, arrow depends on grpc).
+# 2. If something fails, the docker cache at that point gets invalidated;
+#    so it makes sense to put more brittle stuff later on.
+# We mount bind below to avoid copying over a script that we don't want to linger in the image.
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean protobuf"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean re2"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean protobuf"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean gflags"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean absl"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean cares"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean zlib"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean grpc"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean immer"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh --clean arrow"
+RUN --mount=type=bind,source=build-dependencies.sh,target=/build-dependencies.sh \
+    set -eux; bash -c "/build-dependencies.sh env"
 
 #
 # Build client library.
